#ifndef UNNAMED_PROJECT_GAME_LOGIC_FACTORIES_PRECONDITION_FACTORY_H
#define UNNAMED_PROJECT_GAME_LOGIC_FACTORIES_PRECONDITION_FACTORY_H

class PreconditionFactory
{
public:
    PreconditionBase *createFromString();
};

#endif // UNNAMED_PROJECT_GAME_LOGIC_FACTORIES_PRECONDITION_FACTORY_H
